name: Release

on:
  push:
    branches: [release]

env:
  NX_BRANCH: ${GITHUB_REF##*/}

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: major

      - name: echo new tag
        run: |
          echo "${{ steps.taggerDryRun.outputs.new_tag }}"
